first PR
AngryKirill/Pets pull request #1
Opened 2022-07-04 15:19 UTC by AngryKirill

2022-07-04 15:24 UTC, hromau requested changes

2022-07-04 15:24 UTC, hromau commented on Pets.API/Controllers/WeatherForecastController.cs
> +    public class WeatherForecastController : ControllerBase
remove

2022-07-04 15:38 UTC, stas1408123 approved these changes

2022-07-05 09:39 UTC, hromau approved these changes

2022-07-05 09:39 UTC, merged