Add 3-layer architect
AngryKirill/Pets pull request #5
Opened 2022-07-07 12:09 UTC by AngryKirill

2022-07-07 12:19 UTC, hromau requested changes

2022-07-07 12:19 UTC, hromau commented on Pets.API/Controllers/PetController.cs
> +using Pets.DAL.Entities;
api shouldn't know about dal layer, isn't it?

2022-07-07 12:19 UTC, hromau commented on Pets.DAL/Interfaces/IPetRepository.cs
> +    public interface IPetRepository<Pet>
why u use here generic type? is ur repo generic ?

2022-07-07 12:24 UTC, ArtyomBanchikov commented on Pets.API/Controllers/PetController.cs
> +using Pets.DAL.Entities;
This is temporary to avoid mistakes in project

2022-07-07 13:01 UTC, stas1408123 requested changes

2022-07-07 13:01 UTC, stas1408123 commented on Pets.API/Controllers/PetController.cs
> +        public IEnumerable<PetEntity> GetAll()
Don't touch Controller now

2022-07-08 10:20 UTC, AngryKirill commented on Pets.API/Controllers/PetController.cs
> +        public IEnumerable<PetEntity> GetAll()
It automatically renamed in all files

2022-07-08 11:40 UTC, stas1408123 requested changes

2022-07-08 11:40 UTC, stas1408123 commented on Pets.API/Controllers/PetController.cs
> +        public IEnumerable<PetEntity> GetAll()
PetViewModel

2022-07-08 11:40 UTC, stas1408123 commented on Pets.API/Controllers/PetController.cs
> +        public IEnumerable<PetEntity> GetAll()
Add folder ViewModels

2022-07-08 11:40 UTC, stas1408123 commented on Pets.BLL/Services/PetService.cs
> +            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<PetEntity, Pet>()).CreateMapper();
Mayby should put mapper in constructor?
What do you think about if?

2022-07-08 11:53 UTC, stas1408123 commented
It is working?)

2022-07-11 08:29 UTC, hromau requested changes

2022-07-11 08:29 UTC, hromau commented on Pets.API/Controllers/PetController.cs
> +            return _mapper.Map<IEnumerable<Pet>, IEnumerable<PetViewModel>>(Service.GetAll());
looks like spaghetti-code. try to split it a little bit

2022-07-11 08:29 UTC, hromau commented on Pets.BLL/Services/PetService.cs
> +    internal class PetService: IPetService
why internal?

2022-07-11 08:29 UTC, hromau commented on Pets.BLL/Services/PetService.cs
> +        IPetRepository Repository { get; set; }
why not private?
and readonly?

2022-07-11 08:29 UTC, hromau commented on Pets.BLL/Services/PetService.cs
> +        IPetRepository Repository { get; set; }
and it should be a Field

2022-07-11 08:46 UTC, ArtyomBanchikov commented on Pets.BLL/Services/PetService.cs
> +    internal class PetService: IPetService
forgot to change

2022-07-11 08:57 UTC, stas1408123 approved these changes

2022-07-11 09:23 UTC, hromau requested changes

2022-07-11 09:23 UTC, hromau commented on Pets.API/Controllers/PetController.cs
> +                .GetAll());
kek))) 
var allPets = _service.GetAll(); return _mapper.Map ......

2022-07-11 09:24 UTC, hromau requested changes

2022-07-11 09:24 UTC, hromau commented on Pets.API/Controllers/PetController.cs
> +                .Map<IEnumerable<Pet>, IEnumerable<PetViewModel>>(_service
i mean var allPets = service.GetAll(); return mapper.MAp().......

2022-07-11 09:52 UTC, hromau approved these changes

2022-07-11 09:58 UTC, merged